version: '3'
services:
  web:
    build: .
    ports:
    - "8080:8080"
    depends_on:
      - database
  database:
    image: mysql:latest
    ports:
    - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: database
